### ISSUE TITLE
Cannot compile with cuda 13.0 (BART uses deprecated error codes)

### ISSUE THREAD

**Issue by dabosch** [mrirecon/bart#359]
Hi,

I'm on a fresh install of Alma Linux 9 and I have cuda 13.0.
It seems like Bart cannot be compiled with cuda. One issue is in `src/num/fft-cuda.c` lines 56-77. According to the [Nvidia cufft docu](https://docs.nvidia.com/cuda/cufft/#deprecated-functionality) , "The following error codes have been removed: CUFFT_INCOMPLETE_PARAMETER_LIST, CUFFT_PARSE_ERROR, CUFFT_LICENSE_ERROR."

This is an easy fix. But there is another problem, cudaMemPrefetchAsync seems to have changed its interface:

```
/home/dbadmin/bart/src/num/gpuops.c:323:89: error: incompatible type for argument 4 of ‘cudaMemAdvise’
  323 |                         CUDA_ERROR(cudaMemAdvise(ptr, size, cudaMemAdviseSetAccessedBy, cuda_device_id));
      |                                                                                         ^~~~~~~~~~~~~~
      |                                                                                         |
      |                                                                                         int
/home/dbadmin/bart/src/num/gpuops.h:13:66: note: in definition of macro ‘CUDA_ERROR’
   13 | #define CUDA_ERROR(x)                   ({ cudaError_t errval = (x); if (cudaSuccess != errval) cuda_error(__FILE__, __LINE__, errval); })
      |                                                                  ^
In file included from /home/dbadmin/bart/src/num/gpuops.c:25:
/usr/local/cuda/include/cuda_runtime_api.h:7399:140: note: expected ‘struct cudaMemLocation’ but argument is of type ‘int’
 7399 | extern __host__ cudaError_t CUDARTAPI cudaMemAdvise(const void *devPtr, size_t count, enum cudaMemoryAdvise advice, struct cudaMemLocation location);
      |                                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/dbadmin/bart/src/num/gpuops.c:324:96: error: incompatible type for argument 4 of ‘cudaMemAdvise’
  324 |                         CUDA_ERROR(cudaMemAdvise(ptr, size, cudaMemAdviseSetPreferredLocation, cuda_device_id));
      |                                                                                                ^~~~~~~~~~~~~~
      |                                                                                                |
      |                                                                                                int
```

I don't know a lot about cuda, but maybe that helps you find a fix.

Best,
Dario
